pipeline {
    agent { label 'ec2-slave'}
    
    stages {
        stage('test') {
            steps {
                script {
                    echo "test!"
                }
            }
        }
    }
}
